### ISSUE TITLE
Installation needs calc11/lib to exist

### ISSUE THREAD

**Issue by mhvk** [casangi/radio_telescope_delay_model#1]
Finally following up on https://github.com/astropy/astropy/pull/10737#issuecomment-720541061, I tried installing the package. Mostly worked, but a clean install does not have an empty `calc11/lib` directory, so setting up creates the library as lib in https://github.com/astropy/astropy/pull/10737#issuecomment-720541061

Should be an easy fix... (and I can probably make a PR to do it, but I normally compile stuff using `Extension` so am less sure here).

**Comment by Jan-Willem** [comment]
Thank you for catching that. I have added an empty calc11/lib folder.
